(()=>{
const D=`${document.currentScript?.src||location.href}`;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>Number.isFinite(n)?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n).replace('Rp ','Rp '):'—';
const pct=n=>Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'—';
const dateObj=s=>new Date(`${s}T00:00:00`);
const dateFmt=s=>dateObj(s).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let DB=null,A=null,currentPeriod=365;
const EMBEDDED={"asset":"Galeri24 1 gram","source":"embedded fallback","updated_at":"2026-09-09","prices":[{"date":"2025-09-08","sell":2050000,"buyback":null},{"date":"2025-09-30","sell":2209000,"buyback":null},{"date":"2025-10-31","sell":2391000,"buyback":null},{"date":"2025-11-28","sell":2426000,"buyback":null},{"date":"2026-01-30","sell":3260000,"buyback":null},{"date":"2026-02-27","sell":3065000,"buyback":null},{"date":"2026-03-25","sell":2849000,"buyback":null},{"date":"2026-04-20","sell":2886000,"buyback":null},{"date":"2026-04-30","sell":2775000,"buyback":null},{"date":"2026-05-30","sell":2772000,"buyback":null},{"date":"2026-06-22","sell":2649000,"buyback":null},{"date":"2026-07-09","sell":2610000,"buyback":null},{"date":"2026-07-31","sell":2601000,"buyback":null},{"date":"2026-08-01","sell":2573000,"buyback":null},{"date":"2026-08-31","sell":2606000,"buyback":null},{"date":"2026-09-04","sell":2616000,"buyback":null},{"date":"2026-09-07","sell":2576000,"buyback":2432000},{"date":"2026-09-09","sell":2560000,"buyback":2417000}]};
function set(id,val){const e=$('#'+id);if(e)e.textContent=val}
function setHTML(id,val){const e=$('#'+id);if(e)e.innerHTML=val}
function findAtOrBefore(arr,lastDate,days){const target=dateObj(lastDate);target.setDate(target.getDate()-days);let best=null;for(const p of arr){if(dateObj(p.date)<=target)best=p;else break}return best}
function calc(prices){
 prices=[...prices].filter(p=>p&&p.date&&Number.isFinite(p.sell)).sort((a,b)=>a.date.localeCompare(b.date));
 const last=prices.at(-1), sells=prices.map(p=>p.sell), peak=Math.max(...sells),low=Math.min(...sells),peakPoint=prices.find(p=>p.sell===peak),lowPoint=prices.find(p=>p.sell===low);
 const rate=(days)=>{const ref=findAtOrBefore(prices,last.date,days);return ref?((last.sell/ref.sell)-1)*100:null};
 const m7=rate(7),m30=rate(30),m90=rate(90),yoy=rate(365), prior=prices.at(-2), step=prior?((last.sell/prior.sell)-1)*100:null;
 const bb=Number.isFinite(last.buyback)?last.buyback:null, spread=bb?((last.sell-bb)/last.sell)*100:null, be=bb?((last.sell/bb)-1)*100:null;
 const draw=clamp(Math.round((peak-last.sell)/peak*100),0,100), drawPts=draw>=30?28:draw>=25?23:draw>=20?18:draw>=15?12:draw>=10?7:draw>=5?3:0;
 const momPts=(m30==null?3:(m30<0?10:m30<2?4:m30>8?-7:0))+(m7==null?1:(m7<0?4:m7>4?-3:0));
 const trendPts=yoy==null?3:(yoy>20?5:yoy>10?3:yoy>0?1:-5);
 const spreadPts=spread==null?0:(spread<=4?3:spread<=6?1:-3);
 const score=clamp(Math.round(50+drawPts+momPts+trendPts+spreadPts),0,100);
 const label=score>=80?'STRONG BUY':score>=65?'BUY / ACCUMULATE':score>=50?'WATCH / STAGGER':'WAIT';
 const alloc=score>=85?50:score>=75?40:score>=65?25:score>=55?15:0;
 const zones={starter:Math.round(peak*.80),aggressive:Math.round(peak*.75),extreme:Math.round(peak*.68)};
 const conf=clamp(Math.round(35+Math.min(40,prices.length*2)+ (m30!=null?10:0)+(yoy!=null?10:0)+ (bb?5:0)),35,95);
 return {prices,last,peak,low,peakPoint,lowPoint,m7,m30,m90,yoy,step,buyback:bb,spread,be,draw,score,label,alloc,zones,confidence:conf};
}
function allocationSentence(){return A.score>=80?'Kondisi mendukung akumulasi lebih aktif, tetapi tetap bertahap.':A.score>=65?'Sudah cukup menarik untuk mulai masuk sebagian dana; jangan all-in.':A.score>=50?'Belum cukup kuat untuk agresif; simpan porsi lebih besar untuk level yang lebih menarik.':'Belum ada margin of safety yang cukup; lebih baik menunggu.'}
function nav(){const id=(location.hash||'#dashboard').slice(1)||'dashboard';$$('.page').forEach(p=>p.hidden=p.id!==`page-${id}`);$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
function chart(svg,subset,{mini=false,period=365}={}){
 if(!svg||!subset.length)return;
 const W=mini?860:1400,H=mini?210:560,p=mini?30:70, vals=subset.map(x=>x.sell),min=Math.min(...vals),max=Math.max(...vals),range=(max-min)||1;
 const pts=vals.map((v,i)=>[p+i*(W-2*p)/Math.max(subset.length-1,1),H-p-(v-min)*(H-2*p)/range]);
 const grid=!mini?[0,1,2,3,4].map(i=>{const y=p+i*(H-2*p)/4,v=Math.round(max-range*i/4);return `<line x1="${p}" y1="${y}" x2="${W-p}" y2="${y}" stroke="#e9edf3"/><text x="10" y="${y+5}" font-size="12" fill="#8a96a3">${rupiah(v)}</text>`}).join(''):'';
 const area=`M ${p} ${H-p} ${pts.map(q=>q.join(' ')).join(' L ')} L ${pts.at(-1)[0]} ${H-p} Z`;
 const path=pts.map((q,i)=>(i?'L':'M')+q[0]+' '+q[1]).join(' ');
 let html=grid+`<path d="${area}" fill="#eaf3ff"/><path d="${path}" fill="none" stroke="#246bfe" stroke-width="${mini?4:5}" stroke-linecap="round" stroke-linejoin="round"/>`;
 subset.forEach((d,i)=>{const q=pts[i],cls=i===pts.length-1?' latest':' data-point';html+=`<circle class="${cls}" data-index="${i}" cx="${q[0]}" cy="${q[1]}" r="${mini?5:7}" fill="#fff" stroke="#246bfe" stroke-width="3"><title>${dateFmt(d.date)} · ${rupiah(d.sell)} · Buyback ${rupiah(d.buyback)}</title></circle>`});
 const pi=vals.indexOf(max); if(!mini){const q=pts[pi];html+=`<circle cx="${q[0]}" cy="${q[1]}" r="9" fill="#f4b740"/><text x="${Math.min(q[0]+12,W-210)}" y="${Math.max(24,q[1]-14)}" fill="#9b6f0a" font-size="13" font-weight="800">PEAK · ${rupiah(max)}</text>`}
 if(!mini){[0,Math.floor((subset.length-1)/2),subset.length-1].forEach((i,j)=>html+=`<text x="${pts[i][0]}" y="${H-14}" text-anchor="${j===0?'start':j===2?'end':'middle'}" fill="#8a96a3" font-size="12">${dateFmt(subset[i].date)}</text>`)}
 svg.innerHTML=html;
}
function bindChart(svgId,tooltipId,subset){const svg=$(svgId),tip=$(tooltipId);if(!svg||!tip)return;$$(`${svgId} .data-point, ${svgId} .latest`).forEach(pt=>{const show=()=>{const i=+pt.dataset.index,d=subset[i],prev=subset[i-1],delta=prev?((d.sell/prev.sell)-1)*100:null;tip.innerHTML=`<strong>${dateFmt(d.date)}</strong><div>Harga jual <b>${rupiah(d.sell)}</b></div><div>Buyback <b>${rupiah(d.buyback)}</b></div><div>Perubahan <b>${pct(delta)}</b></div>`;const sr=svg.getBoundingClientRect(),pr=pt.getBoundingClientRect();tip.style.left=Math.max(10,pr.left-sr.left+16)+'px';tip.style.top=Math.max(10,pr.top-sr.top-8-tip.offsetHeight)+'px';tip.hidden=false};pt.addEventListener('pointerenter',show);pt.addEventListener('click',show);pt.addEventListener('focus',show);pt.setAttribute('tabindex','0')});svg.addEventListener('pointerleave',()=>tip.hidden=true)}
function updateDashboard(){
 set('heroDate',dateFmt(A.last.date));set('topUpdated',`Update ${dateFmt(A.last.date)}`);set('sourceLabel',`Sumber: ${DB.source||'Gold Advisor'}`);set('price',rupiah(A.last.sell));set('buybackDash',rupiah(A.buyback));set('todayMove',pct(A.step));set('miniNote',`Harga ${A.step<0?'turun':'naik'} ${Math.abs(A.step||0).toFixed(2)}% dari snapshot sebelumnya.`);set('score',A.score);set('scoreBadge',A.label);set('decisionHeadline',A.label);set('decisionText',allocationSentence());set('allocPct',A.alloc+'%');set('allocationReason',allocationSentence());set('actionLabel',A.alloc?`${A.alloc}% SEKARANG`:'TUNGGU');set('allocExample',rupiah(5000000*A.alloc/100));set('allocGram',`${(5000000*A.alloc/100/A.last.sell).toFixed(2)} g`);set('quickDd',`-${A.draw.toFixed(1)}%`);set('quick30',pct(A.m30));set('quickYoy',pct(A.yoy));set('quickSpread',pct(A.spread));set('insightCorrection',`Harga ${A.draw.toFixed(1)}% di bawah peak ${rupiah(A.peak)}.`);set('insightMomentum',A.m30==null?'Belum ada titik tepat 30 hari lalu.':`30 hari ${pct(A.m30)}.`);set('insightSpread',A.spread==null?'Buyback terbaru belum tersedia.':`Spread ${A.spread.toFixed(2)}%; perlu kenaikan serupa untuk melewati spread.`);const ladder=[['starter','CICIL',A.zones.starter,'Masuk sebagian'],['aggressive','AGRESIF',A.zones.aggressive,'Tambah jika turun'],['extreme','EKSTREM',A.zones.extreme,'Gunakan cadangan']];setHTML('ladderRows',ladder.map(x=>`<div class="ladder-row"><span class="ladder-badge ${x[0]}">${x[1]}</span><div><b>${rupiah(x[2])}</b><span>${x[3]}</span></div><strong>${A.last.sell<=x[2]?'aktif':'—'}</strong></div>`).join(''));const mini=A.prices.slice(-10);chart($('#miniChart'),mini,{mini:true});bindChart('#miniChart','#miniTip',mini)}
function updateMarket(period=365){currentPeriod=period;const cutoff=dateObj(A.last.date);cutoff.setDate(cutoff.getDate()-period);const subset=A.prices.filter(p=>dateObj(p.date)>=cutoff);chart($('#mainChart'),subset,{period});bindChart('#mainChart','#mainTooltip',subset);set('chartTitle',period===365?'Pergerakan 1 tahun':`Pergerakan ${period} hari`);$$('#periodTabs button').forEach(b=>b.classList.toggle('active',+b.dataset.period===period));set('marketCurrent',rupiah(A.last.sell));set('marketDate',dateFmt(A.last.date));set('peak',rupiah(A.peak));set('peakDate',dateFmt(A.peakPoint.date));set('trough',rupiah(A.low));set('troughDate',dateFmt(A.lowPoint.date));set('marketDd',`-${A.draw.toFixed(1)}%`);set('historyCount',`${A.prices.length} titik data`);const ref=period===365?A.yoy:period===90?A.m90:A.m30;set('chartReading',`${dateFmt(A.last.date)}: harga jual ${rupiah(A.last.sell)}. Posisi sekarang ${A.draw.toFixed(1)}% di bawah peak. ${ref==null?'Belum ada snapshot tepat pada awal periode ini.':`Perubahan periode ${pct(ref)}.`} ${A.step<0?'Titik terakhir masih menunjukkan pelemahan.':'Titik terakhir menunjukkan kenaikan.'}`);setHTML('historyRows',[...A.prices].reverse().map((d,i,arr)=>{const prev=arr[i+1],delta=prev?((d.sell/prev.sell)-1)*100:null;return `<tr><td>${dateFmt(d.date)}</td><td>${rupiah(d.sell)}</td><td>${rupiah(d.buyback)}</td><td class="${delta<0?'down':'up'}">${pct(delta)}</td><td><span class="status-pill ${delta<0?'down':''}">${delta==null?'Awal':delta<0?'Turun':'Naik'}</span></td></tr>`}).join(''))}
function updateDecision(){set('decisionChip',A.label);set('bigSignal',A.label);set('bigSignalText',allocationSentence());set('dScore',A.score);set('dConfidence',A.confidence+'%');set('dBuy',rupiah(A.last.sell));set('dBb',rupiah(A.buyback));set('dSpread',pct(A.spread));set('dBe',A.buyback?rupiah(A.last.sell*(1+A.be/100)): 'Belum tersedia');set('beText',A.buyback?`Dengan buyback ${rupiah(A.buyback)}, harga perlu naik sekitar ${A.be.toFixed(2)}% untuk menyamai nilai buyback saat ini.`:'Belum ada buyback terbaru untuk menghitung break-even.');const factors=[['Koreksi',clamp(50+A.draw*2,0,100),`Harga ${A.draw.toFixed(1)}% di bawah peak.`],['Momentum',clamp(50+(A.momScore||0)*4,0,100),A.m30==null?'Data 30 hari belum lengkap.':`30 hari ${pct(A.m30)}.`],['Tren 1 tahun',clamp(50+(A.trendPts||0)*7,0,100),A.yoy==null?'Data 1 tahun belum lengkap.':`Perubahan 1 tahun ${pct(A.yoy)}.`],['Spread',clamp(50+((A.spread!=null)?(A.spread<=4?15:A.spread<=6?5:-15):0),0,100),A.spread==null?'Buyback belum tersedia.':`Spread ${A.spread.toFixed(2)}%.`]];setHTML('factorGrid',factors.map(f=>`<article class="factor-card"><div class="factor-top"><b>${f[0]}</b><span>${Math.round(f[1])}</span></div><div class="factor-bar"><i style="width:${f[1]}%"></i></div><p>${f[2]}</p></article>`).join(''));setHTML('scenarioBoxes',[['Turun 5%',A.last.sell*.95],['Turun 10%',A.last.sell*.90],['Ke peak',A.peak],['Entry agresif',A.zones.aggressive]].map(x=>`<div class="scenario-box"><span>${x[0]}</span><b>${rupiah(Math.round(x[1]))}</b></div>`).join(''))}
function updateSimulator(){const budget=Math.max(0,Number($('#budget')?.value)||0),alloc=Math.max(0,Number($('#allocInput')?.value)||0),now=budget*alloc/100;set('allocValue',alloc+'%');set('engineAlloc',A.alloc+'%');set('simHeadline',alloc?`Beli ${rupiah(now)} sekarang`:'Tahan dana untuk level berikutnya');set('simText',alloc===A.alloc?'Sama dengan porsi engine saat ini.':`Porsi ${alloc}% berbeda dari engine ${A.alloc}%; slider dipakai untuk simulasi.`);set('simNow',rupiah(now));set('simGram',A.last.sell?(now/A.last.sell).toFixed(3)+' g':'—');set('simRemain',rupiah(budget-now));setHTML('planRows',[{n:'Masuk',p:A.last.sell,x:alloc,why:'Harga saat ini'},{n:'Tambah 1',p:A.zones.aggressive,x:Math.min(30,100-alloc),why:'Zona agresif'},{n:'Cadangan',p:A.zones.extreme,x:Math.max(0,100-alloc-Math.min(30,100-alloc)),why:'Zona ekstrem'}].map(r=>`<div class="plan-row"><span>${r.n}</span><div><b>${rupiah(r.p)}</b><small>${r.why}</small></div><span>${r.x}%</span><b>${rupiah(budget*r.x/100)}</b></div>`).join(''))}
async function load(){
 let source='embedded fallback';try{const path=new URL('./data/prices.json',document.baseURI).href;const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const j=await r.json();if(!j.prices?.length)throw new Error('empty');DB=j;source=j.source||'dataset'}catch(e){DB=JSON.parse(JSON.stringify(EMBEDDED));DB.source=source}
 DB.prices=DB.prices.filter(p=>p&&p.date&&Number.isFinite(p.sell));A=calc(DB.prices);window.GOLD_ADVISOR={DB,A};
 // expose the extra components for method view
 const ref= A.yoy; A.momScore=(A.m30==null?3:(A.m30<0?10:A.m30<2?4:A.m30>8?-7:0))+(A.m7==null?1:(A.m7<0?4:A.m7>4?-3:0)); A.trendPts=ref==null?3:(ref>20?5:ref>10?3:ref>0?1:-5);
 updateDashboard();updateMarket();updateDecision();updateSimulator();set('methodDataNote',`Saat ini ada ${A.prices.length} titik data dari ${dateFmt(A.prices[0].date)} sampai ${dateFmt(A.last.date)}. Harga terbaru yang dipakai adalah ${rupiah(A.last.sell)} pada ${dateFmt(A.last.date)}. Data harian penuh belum tersedia, sehingga indikator periode hanya dihitung jika ada titik pada/before tanggal target.`);set('methodSource',source);set('methodConfidence',A.confidence+'%');
}
function init(){nav();$$('[data-page]').forEach(a=>a.addEventListener('click',()=>setTimeout(nav,0)));$('#periodTabs')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b)updateMarket(+b.dataset.period)});$('#allocInput')?.addEventListener('input',updateSimulator);$('#budget')?.addEventListener('input',updateSimulator);$('#calcBtn')?.addEventListener('click',updateSimulator);window.addEventListener('hashchange',nav);load().catch(e=>console.error(e));}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
