(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>Number.isFinite(n)?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n).replace('Rp ','Rp '):'—';
const pct=n=>Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'—';
const dateObj=s=>new Date(`${s}T00:00:00`);
const dateFmt=s=>dateObj(s).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};
const setHTML=(id,v)=>{const e=$('#'+id);if(e)e.innerHTML=v};
const esc=v=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let DB=null,A=null,currentPeriod=365;
const EMBEDDED={asset:'Galeri24 1 gram',source:'embedded fallback',updated_at:'2026-09-09',prices:[
{date:'2025-09-08',sell:2050000,buyback:null},{date:'2025-09-30',sell:2209000,buyback:null},{date:'2025-10-31',sell:2391000,buyback:null},{date:'2025-11-28',sell:2426000,buyback:null},{date:'2026-01-30',sell:3260000,buyback:null},{date:'2026-02-27',sell:3065000,buyback:null},{date:'2026-03-25',sell:2849000,buyback:null},{date:'2026-04-20',sell:2886000,buyback:null},{date:'2026-04-30',sell:2775000,buyback:null},{date:'2026-05-30',sell:2772000,buyback:null},{date:'2026-06-22',sell:2649000,buyback:null},{date:'2026-07-09',sell:2610000,buyback:null},{date:'2026-07-31',sell:2601000,buyback:null},{date:'2026-08-01',sell:2573000,buyback:null},{date:'2026-08-31',sell:2606000,buyback:null},{date:'2026-09-04',sell:2616000,buyback:null},{date:'2026-09-07',sell:2576000,buyback:2432000},{date:'2026-09-09',sell:2560000,buyback:2417000}]};
function normalized(prices){return [...(prices||[])].filter(p=>p&&/^\d{4}-\d{2}-\d{2}$/.test(p.date)&&Number.isFinite(p.sell)).sort((a,b)=>a.date.localeCompare(b.date));}
function atOrBefore(arr,date,days){const target=dateObj(date);target.setDate(target.getDate()-days);let best=null;for(const p of arr){if(dateObj(p.date)<=target)best=p;else break}return best;}
function atOrAfter(arr,date,days){const target=dateObj(date);target.setDate(target.getDate()+days);return arr.find(p=>dateObj(p.date)>=target)||null;}
function changeFrom(a,b){return a&&b&&b.sell?((a.sell/b.sell)-1)*100:null;}
function scoreAt(history,index){
 const arr=history.slice(0,index+1), last=arr.at(-1); if(!last)return null;
 const sells=arr.map(p=>p.sell), peak=Math.max(...sells), prior=arr.at(-2); const m7=(()=>{const r=atOrBefore(arr,last.date,7);return changeFrom(last,r)})();
 const m30=(()=>{const r=atOrBefore(arr,last.date,30);return changeFrom(last,r)})();
 const yoy=(()=>{const r=atOrBefore(arr,last.date,365);return changeFrom(last,r)})();
 const buyback=Number.isFinite(last.buyback)?last.buyback:null, spread=buyback?((last.sell-buyback)/last.sell)*100:null;
 const draw=(peak-last.sell)/peak*100;
 const drawPts=draw>=30?28:draw>=25?23:draw>=20?18:draw>=15?12:draw>=10?7:draw>=5?3:0;
 const momPts=(m30==null?3:(m30<0?10:m30<2?4:m30>8?-7:0))+(m7==null?1:(m7<0?4:m7>4?-3:0));
 const trendPts=yoy==null?3:(yoy>20?5:yoy>10?3:yoy>0?1:-5);
 const spreadPts=spread==null?0:(spread<=4?3:spread<=6?1:-3);
 const score=clamp(Math.round(50+drawPts+momPts+trendPts+spreadPts),0,100);
 const label=score>=80?'STRONG BUY':score>=65?'BUY / ACCUMULATE':score>=50?'WATCH / STAGGER':'WAIT';
 const alloc=score>=85?50:score>=75?40:score>=65?25:score>=55?15:0;
 return {last,peak,m7,m30,yoy,spread,draw,score,label,alloc};
}
function calc(prices){
 const p=normalized(prices); const last=p.at(-1); if(!last)throw new Error('Dataset kosong'); const sells=p.map(x=>x.sell); const peak=Math.max(...sells),low=Math.min(...sells); const peakPoint=p.find(x=>x.sell===peak),lowPoint=p.find(x=>x.sell===low);
 const m7=changeFrom(last,atOrBefore(p,last.date,7)),m30=changeFrom(last,atOrBefore(p,last.date,30)),m90=changeFrom(last,atOrBefore(p,last.date,90)),yoy=changeFrom(last,atOrBefore(p,last.date,365));
 const prior=p.at(-2),step=changeFrom(last,prior); const buyback=Number.isFinite(last.buyback)?last.buyback:null,spread=buyback?((last.sell-buyback)/last.sell)*100:null,be=buyback?((last.sell/buyback)-1)*100:null; const draw=(peak-last.sell)/peak*100;
 const drawPts=draw>=30?28:draw>=25?23:draw>=20?18:draw>=15?12:draw>=10?7:draw>=5?3:0;
 const momPts=(m30==null?3:(m30<0?10:m30<2?4:m30>8?-7:0))+(m7==null?1:(m7<0?4:m7>4?-3:0));
 const trendPts=yoy==null?3:(yoy>20?5:yoy>10?3:yoy>0?1:-5);
 const spreadPts=spread==null?0:(spread<=4?3:spread<=6?1:-3);
 const score=clamp(Math.round(50+drawPts+momPts+trendPts+spreadPts),0,100),label=score>=80?'STRONG BUY':score>=65?'BUY / ACCUMULATE':score>=50?'WATCH / STAGGER':'WAIT',alloc=score>=85?50:score>=75?40:score>=65?25:score>=55?15:0;
 const zones={starter:Math.round(peak*.8),aggressive:Math.round(peak*.75),extreme:Math.round(peak*.68)};
 const confidence=clamp(Math.round(30+Math.min(45,p.length*2.2)+(m30!=null?8:0)+(yoy!=null?8:0)+(buyback?6:0)),30,95);
 const replay=replayStats(p);
 return {prices:p,last,peak,low,peakPoint,lowPoint,m7,m30,m90,yoy,step,buyback,spread,be,draw,score,label,alloc,zones,confidence,momPts,trendPts,replay};
}
function decisionText(){return A.score>=80?'Kondisi mendukung akumulasi lebih aktif, tetapi tetap bertahap.':A.score>=65?'Sudah cukup menarik untuk mulai masuk sebagian dana; jangan all-in.':A.score>=50?'Belum cukup kuat untuk agresif; simpan porsi lebih besar untuk level yang lebih menarik.':'Belum ada margin of safety yang cukup; lebih baik menunggu.';}
function replayStats(history){
 const horizons=[30,90].map(days=>{const rows=[]; for(let i=0;i<history.length;i++){const s=scoreAt(history,i);if(!s)continue;const future=atOrAfter(history,history[i].date,days);if(!future)continue;rows.push({score:s.score,label:s.label,ret:changeFrom(future,history[i])});} const avg=rows.length?rows.reduce((a,r)=>a+r.ret,0)/rows.length:null;const wins=rows.length?rows.filter(r=>r.ret>0).length/rows.length*100:null;const buys=rows.filter(r=>r.score>=65);const buyAvg=buys.length?buys.reduce((a,r)=>a+r.ret,0)/buys.length:null;return {days,n:rows.length,avg,wins,buyN:buys.length,buyAvg};});return {d30:horizons[0],d90:horizons[1]};
}
function allocationSentence(){const budget=5000000,nom=budget*A.alloc/100,grams=nom/A.last.sell;return {nom,grams};}
function nav(){let id=(location.hash||'#dashboard').slice(1)||'dashboard';if(!['dashboard','market','decision','simulator','method'].includes(id))id='dashboard';$$('.page').forEach(p=>p.hidden=p.id!==`page-${id}`);$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});}
function chart(svg,subset,{mini=false}={}){if(!svg||!subset.length)return; const W=mini?900:1500,H=mini?220:580,pad=mini?24:72,vals=subset.map(x=>x.sell),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1; const pts=vals.map((v,i)=>[pad+i*(W-2*pad)/Math.max(1,subset.length-1),H-pad-(v-min)*(H-2*pad)/range]); const grid=mini?'':[0,1,2,3,4].map(i=>{const y=pad+i*(H-2*pad)/4,v=Math.round(max-range*i/4);return `<line x1="${pad}" y1="${y}" x2="${W-pad}" y2="${y}" stroke="#e8eef5"/><text x="8" y="${y+4}" fill="#8c98a8" font-size="12">${rupiah(v)}</text>`}).join(''); const path=pts.map((q,i)=>(i?'L':'M')+q[0]+' '+q[1]).join(' '), area=`M ${pad} ${H-pad} ${pts.map(q=>q.join(' ')).join(' L ')} L ${pts.at(-1)[0]} ${H-pad} Z`; let html=grid+`<path d="${area}" fill="#eaf3ff"/><path d="${path}" fill="none" stroke="#2b74e8" stroke-width="${mini?4:5}" stroke-linecap="round" stroke-linejoin="round"/>`; subset.forEach((d,i)=>{const q=pts[i];html+=`<circle class="point" data-index="${i}" cx="${q[0]}" cy="${q[1]}" r="${mini?5:7}" fill="#fff" stroke="#2b74e8" stroke-width="3"/>`}); if(!mini){const pi=vals.indexOf(max),q=pts[pi];html+=`<circle cx="${q[0]}" cy="${q[1]}" r="10" fill="#f4b740"/><text x="${Math.min(q[0]+12,W-220)}" y="${Math.max(24,q[1]-16)}" fill="#9b6f0a" font-size="13" font-weight="800">PEAK · ${rupiah(max)}</text>`; [0,Math.floor((subset.length-1)/2),subset.length-1].forEach((i,j)=>html+=`<text x="${pts[i][0]}" y="${H-14}" text-anchor="${j===0?'start':j===2?'end':'middle'}" fill="#8c98a8" font-size="12">${dateFmt(subset[i].date)}</text>`)} svg.innerHTML=html; bindChart(svg,subset);}
function bindChart(svg,subset){const tip=svg.parentElement?.querySelector('.chart-tip');if(!tip)return; svg.querySelectorAll('.point').forEach(pt=>{const show=()=>{const i=+pt.dataset.index,d=subset[i],prev=subset[i-1],delta=changeFrom(d,prev);tip.innerHTML=`<strong>${dateFmt(d.date)}</strong><div>Harga jual <b>${rupiah(d.sell)}</b></div><div>Buyback <b>${rupiah(d.buyback)}</b></div><div>Perubahan <b>${pct(delta)}</b></div>`;const sr=svg.getBoundingClientRect(),pr=pt.getBoundingClientRect();tip.style.left=Math.max(10,pr.left-sr.left+14)+'px';tip.style.top=Math.max(8,pr.top-sr.top-10-tip.offsetHeight)+'px';tip.hidden=false};pt.addEventListener('pointerenter',show);pt.addEventListener('click',show);pt.addEventListener('focus',show);pt.tabIndex=0});svg.addEventListener('pointerleave',()=>tip.hidden=true);}
function updateDashboard(){const b=allocationSentence();set('heroDate',dateFmt(A.last.date));set('topUpdated',`Update ${dateFmt(A.last.date)}`);set('sourceLabel',`Sumber: ${DB.source||'Gold Advisor'}`);set('price',rupiah(A.last.sell));set('buybackDash',rupiah(A.buyback));set('todayMove',pct(A.step));$('#todayMove')?.classList.toggle('down',A.step<0);set('miniNote',`Harga ${A.step<0?'turun':'naik'} ${Math.abs(A.step||0).toFixed(2)}% dari snapshot sebelumnya.`);set('score',A.score);set('scoreBadge',A.label);set('decisionHeadline',A.label);set('decisionText',decisionText());set('scoreMeterFill','');const meter=$('#scoreMeterFill');if(meter)meter.style.width=A.score+'%';set('allocPct',A.alloc+'%');set('allocationReason',decisionText());set('actionLabel',A.alloc?`${A.alloc}%`: 'TUNGGU');set('actionText',A.alloc?`Mulai dengan ${rupiah(b.nom)} dari Rp5 juta, lalu simpan sisanya untuk level yang lebih rendah.`:'Tahan dana dan tunggu margin of safety yang lebih baik.');set('allocExample',rupiah(b.nom));set('allocGram',`${b.grams.toFixed(2)} g`);set('quickBuyNominal',rupiah(b.nom));set('quickBuyGram',`${b.grams.toFixed(2)} g`);set('quickDd',`-${A.draw.toFixed(1)}%`);set('quick30',pct(A.m30));set('quickYoy',pct(A.yoy));set('quickSpread',pct(A.spread));set('insightCorrection',`Harga ${A.draw.toFixed(1)}% di bawah peak ${rupiah(A.peak)}.`);set('insightMomentum',A.m30==null?'Belum ada titik historis yang cukup dekat untuk 30 hari.':`Perubahan 30 hari ${pct(A.m30)}.`);set('insightSpread',A.spread==null?'Buyback terbaru belum tersedia.':`Spread ${A.spread.toFixed(2)}%; harga perlu mengatasi gap ini sebelum impas.`);const ladder=[['starter','CICIL',A.zones.starter,'Masuk sebagian'],['aggressive','AGRESIF',A.zones.aggressive,'Tambah jika turun'],['extreme','EKSTREM',A.zones.extreme,'Gunakan cadangan']];setHTML('ladderRows',ladder.map(x=>`<div class="ladder-row"><span class="ladder-badge ${x[0]}">${x[1]}</span><div><b>${rupiah(x[2])}</b><small>${x[3]}</small></div><strong>${A.last.sell<=x[2]?'aktif':'—'}</strong></div>`).join(''));chart($('#miniChart'),A.prices.slice(-10),{mini:true});}
function updateMarket(period=365){currentPeriod=period;let cutoff=dateObj(A.last.date);cutoff.setDate(cutoff.getDate()-period);const subset=A.prices.filter(p=>dateObj(p.date)>=cutoff);chart($('#mainChart'),subset,{mini:false});set('chartTitle',period===365?'Pergerakan 1 tahun':`Pergerakan ${period} hari`);$$('#periodTabs button').forEach(b=>b.classList.toggle('active',+b.dataset.period===period));set('marketCurrent',rupiah(A.last.sell));set('marketDate',dateFmt(A.last.date));set('peak',rupiah(A.peak));set('peakDate',dateFmt(A.peakPoint.date));set('trough',rupiah(A.low));set('troughDate',dateFmt(A.lowPoint.date));set('marketDd',`-${A.draw.toFixed(1)}%`);set('historyCount',`${A.prices.length} titik data`);const ref=period===365?A.yoy:period===90?A.m90:A.m30;const refText=ref==null?'Belum ada titik historis yang tepat di awal periode ini.':`Perubahan periode ${pct(ref)}.`;set('chartReading',`Harga terakhir ${rupiah(A.last.sell)} pada ${dateFmt(A.last.date)}. Saat ini ${A.draw.toFixed(1)}% di bawah peak. ${refText} ${A.step<0?'Snapshot terakhir masih melemah.':'Snapshot terakhir menguat.'}`);const rows=[...A.prices].reverse();setHTML('historyRows',rows.map((d,i,arr)=>{const prev=arr[i+1],delta=changeFrom(d,prev);const cls=delta<0?'down':'up';return `<tr><td>${dateFmt(d.date)}</td><td>${rupiah(d.sell)}</td><td>${rupiah(d.buyback)}</td><td class="${cls}">${pct(delta)}</td><td><span class="status-pill ${delta<0?'down':''}">${delta==null?'Awal':delta<0?'Turun':'Naik'}</span></td></tr>`}).join(''));}
function updateDecision(){set('decisionChip',A.label);set('bigSignal',A.label);set('bigSignalText',decisionText());set('dScore',A.score);set('dConfidence',A.confidence+'%');set('dBuy',rupiah(A.last.sell));set('dBb',rupiah(A.buyback));set('dSpread',pct(A.spread));set('dBe',A.buyback?rupiah(A.last.sell*(1+A.be/100)):'Belum tersedia');set('beText',A.buyback?`Dengan buyback ${rupiah(A.buyback)}, harga perlu naik sekitar ${A.be.toFixed(2)}% untuk menyamai nilai buyback saat ini.`:'Belum ada buyback terbaru untuk menghitung break-even.');const factors=[['Koreksi',clamp(50+A.draw*2,0,100),`Harga ${A.draw.toFixed(1)}% di bawah peak.`],['Momentum',clamp(50+A.momPts*4,0,100),A.m30==null?'Data 30 hari belum cukup padat.':`Perubahan 30 hari ${pct(A.m30)}.`],['Tren 1 tahun',clamp(50+A.trendPts*7,0,100),A.yoy==null?'Data 1 tahun belum cukup padat.':`Perubahan 1 tahun ${pct(A.yoy)}.`],['Spread',clamp(50+((A.spread!=null)?(A.spread<=4?15:A.spread<=6?5:-15):0),0,100),A.spread==null?'Buyback belum tersedia.':`Spread ${A.spread.toFixed(2)}%.`]];setHTML('factorGrid',factors.map(f=>`<article class="factor-card"><div class="factor-top"><b>${f[0]}</b><span>${Math.round(f[1])}</span></div><div class="factor-bar"><i style="width:${f[1]}%"></i></div><p>${f[2]}</p></article>`).join(''));const ladder=[['CICIL',A.zones.starter,'Mulai porsi awal'],['AGRESIF',A.zones.aggressive,'Tambah saat lebih murah'],['EKSTREM',A.zones.extreme,'Gunakan dana cadangan']];setHTML('decisionLadder',ladder.map((x,i)=>`<div class="dl-row"><span class="ladder-badge ${i===0?'starter':i===1?'aggressive':'extreme'}">${x[0]}</span><div><b class="dl-price">${rupiah(x[1])}</b><div class="dl-desc">${x[2]}</div></div><b>${A.last.sell<=x[1]?'AKTIF':'—'}</b></div>`).join(''));const r30=A.replay.d30,r90=A.replay.d90;set('replay30N',r30.n);set('replay30Avg',pct(r30.avg));set('replay30Win',r30.wins==null?'—':r30.wins.toFixed(0)+'%');set('replay90N',r90.n);set('replayNote',`Replay menggunakan ${r30.n} observasi dengan horizon 30 hari dan ${r90.n} observasi untuk 90 hari. Untuk sinyal score ≥65, rata-rata return ke titik masa depan terdekat adalah ${pct(r30.buyAvg)} (30 hari) dan ${pct(r90.buyAvg)} (90 hari) bila tersedia. Karena histori masih sparse, hasil ini bersifat eksploratif, bukan bukti prediktif.`);setHTML('scenarioBoxes',[['Turun 5%',A.last.sell*.95],['Turun 10%',A.last.sell*.90],['Ke peak',A.peak],['Entry agresif',A.zones.aggressive]].map(x=>`<div class="scenario-box"><span>${x[0]}</span><b>${rupiah(Math.round(x[1]))}</b></div>`).join(''));}
function updateSimulator(){const budget=Math.max(0,Number($('#budget')?.value)||0),alloc=Math.max(0,Math.min(100,Number($('#allocInput')?.value)||0));const now=budget*alloc/100,grams=A.last.sell?now/A.last.sell:0;set('allocValue',alloc+'%');set('engineAlloc',A.alloc+'%');set('simHeadline',alloc?`Beli ${rupiah(now)} sekarang`:'Tahan dana untuk level berikutnya');set('simText',alloc===A.alloc?'Sama dengan porsi engine saat ini.':`Porsi ${alloc}% berbeda dari engine ${A.alloc}%; slider dipakai untuk simulasi manual.`);set('simNow',rupiah(now));set('simGram',grams.toFixed(3)+' g');set('simRemain',rupiah(budget-now));const p1=alloc,p2=Math.min(30,Math.max(0,100-p1)),p3=Math.max(0,100-p1-p2);const rows=[{n:'Masuk',p:A.last.sell,x:p1,why:'Harga sekarang'},{n:'Tambah 1',p:A.zones.aggressive,x:p2,why:'Zona agresif'},{n:'Cadangan',p:A.zones.extreme,x:p3,why:'Zona ekstrem'}];setHTML('planRows',rows.map(r=>`<div class="plan-row"><span>${r.n}</span><div><b>${rupiah(r.p)}</b><small>${r.why}</small></div><span>${r.x}%</span><b>${rupiah(budget*r.x/100)}</b></div>`).join(''));}
function updateMethod(){set('methodDataSummary',`${A.prices.length} titik data`);set('methodDataNote',`${dateFmt(A.prices[0].date)} sampai ${dateFmt(A.last.date)}. Harga terbaru ${rupiah(A.last.sell)}. Periode dihitung berdasarkan tanggal aktual yang tersedia; data kosong tidak diestimasi.`);set('methodConfidence',A.confidence+'%');}
async function load(){let source='embedded fallback';try{const url=new URL('./data/prices.json',document.baseURI).href;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const j=await r.json();if(!j.prices||!j.prices.length)throw new Error('empty');DB=j;source=j.source||'dataset';}catch(err){DB=JSON.parse(JSON.stringify(EMBEDDED));DB.source=source;const b=$('#dataBanner');if(b){b.hidden=false;b.textContent='Dataset eksternal tidak terbaca saat ini. Gold Advisor memakai salinan data internal yang aman agar semua halaman tetap bisa digunakan.';}}
DB.prices=normalized(DB.prices);A=calc(DB.prices);window.GOLD_ADVISOR={DB,A};if(DB.source!=='embedded fallback'){const b=$('#dataBanner');if(b){b.hidden=false;b.classList.add('good');b.textContent=`Data aktif: ${DB.source||'dataset'} · ${A.prices.length} titik · ${dateFmt(A.last.date)}.`;}}
updateDashboard();updateMarket();updateDecision();updateSimulator();updateMethod();}
function init(){nav();$$('.nav-link').forEach(a=>a.addEventListener('click',()=>setTimeout(nav,0)));$('#periodTabs')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b)updateMarket(+b.dataset.period)});$('#allocInput')?.addEventListener('input',updateSimulator);$('#budget')?.addEventListener('input',updateSimulator);$('#calcBtn')?.addEventListener('click',updateSimulator);window.addEventListener('hashchange',nav);load().catch(err=>{console.error(err);const b=$('#dataBanner');if(b){b.hidden=false;b.textContent='Engine gagal memuat dataset. Periksa console browser.';}})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
